ibtikar_share_economy_payfort_api:
    resource: "@IbtikarShareEconomyPayFortBundle/Resources/config/routing/api.yml"
    prefix:   /api/payfort

ibtikar_share_economy_payfort:
    resource: "@IbtikarShareEconomyPayFortBundle/Resources/config/routing/payfort.yml"
    prefix:   /payfort