services:
    ibtikar.shareeconomy.payfort.integration:
        class: Ibtikar\ShareEconomyPayFortBundle\Service\PayFortIntegration
        arguments: [ "%ibtikar.shareeconomy.payfort.integration.parameters%", "@templating", "@api_caller" ]

    ibtikar.shareeconomy.payfort.relation_subscriber:
        class: Ibtikar\ShareEconomyPayFortBundle\Listener\DynamicRelationSubscriber
        arguments: [ '@translator', '@user_operations' ]
        tags:
            - { name: kernel.event_subscriber }

    ibtikar.shareeconomy.payfort.PaymentMethods:
        class: Ibtikar\ShareEconomyPayFortBundle\Service\PaymentMethods
        arguments:  ["@doctrine.orm.entity_manager"]

    ibtikar.shareeconomy.payfort.transaction_status_service:
        class: Ibtikar\ShareEconomyPayFortBundle\Service\TransactionStatusService
        arguments:  ["@doctrine.orm.entity_manager", "@event_dispatcher"]
        
    ibtikar.shareeconomy.payfort.PaymentOperations:
        class: Ibtikar\ShareEconomyPayFortBundle\Service\PaymentOperations
        arguments:  ["@doctrine.orm.entity_manager", "@ibtikar.shareeconomy.payfort.integration", "@ibtikar.shareeconomy.payfort.transaction_status_service"]