services:
    ibtikar.shareeconomy.payfort.integration:
        class: Ibtikar\ShareEconomyPayFortBundle\Service\PayFortIntegration
        arguments: [ %ibtikar.shareeconomy.payfort.integration.parameters%, "@api_caller" ]