sofra_payfort_transaction_status_update_notification:
    path:     /transaction-status-update-notification
    defaults: { _controller: IbtikarShareEconomyPayFortBundle:OfflineNotificationsReceiver:transactionStatusUpdateNotification }
    methods:  POST